from app.repository.role import RoleRepository
from app.repository.user import UserRepository
from app.repository.patient import PatientRepository
from app.repository.hospital import HospitalRepository
from app.repository.diagnose import DiagnoseRepository
from app.repository.cabinet import CabinetRepository
from app.repository.post import PostRepository
from app.repository.address import AddressRepository
from app.repository.treatment_plan import PatientDoctorDiagnoseRepository
from app.repository.doctor import DoctorRepository
from app.repository.specialization import SpecializationRepository
