class TableNames:
    PATIENT = "patient"
    DOCTOR = "doctor"
    PATIENT_DOCTOR_DIAGNOSE = "patient_doctor_diagnose"
    SESSION = "session"
    NURSE = "nurse"
    USER = "user"
    ROLE = "role"
    DIAGNOSE = "diagnose"
    HOSPITAL = "hospital"
    POST = "post"
    CABINET = "cabinet"
    ADDRESS = "address"
    SPECIALIZATION = "specialization"
