"""init

Revision ID: edfe25653d8b
Revises: 
Create Date: 2026-08-30 16:50:56.917241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edfe25653d8b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('country_name', sa.String(length=256), nullable=False),
    sa.Column('city_name', sa.String(length=256), nullable=False),
    sa.Column('street_name', sa.String(length=256), nullable=False),
    sa.Column('building_number', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_address')),
    sa.UniqueConstraint('country_name', 'city_name', 'street_name', 'building_number', name=op.f('uq_address_country_name'))
    )
    op.create_table('diagnose',
    sa.Column('name', sa.String(length=2048), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnose'))
    )
    op.create_index(op.f('ix_diagnose_name'), 'diagnose', ['name'], unique=True)
    op.create_table('patient',
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('patronymic', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient'))
    )
    op.create_index(op.f('ix_patient_phone'), 'patient', ['phone'], unique=True)
    op.create_table('hospital',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], name=op.f('fk_hospital_address_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hospital')),
    sa.UniqueConstraint('address_id', 'name', 'number', name=op.f('uq_hospital_address_id'))
    )
    op.create_table('cabinet',
    sa.Column('number', sa.String(length=256), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.id'], name=op.f('fk_cabinet_hospital_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cabinet')),
    sa.UniqueConstraint('hospital_id', 'number', name=op.f('uq_cabinet_hospital_id'))
    )
    op.create_table('user',
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('patronymic', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('DOCTOR', 'NURSE', name='userrole', native_enum=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.id'], name=op.f('fk_user_hospital_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], name=op.f('fk_doctor_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctor'))
    )
    op.create_table('nurse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], name=op.f('fk_nurse_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nurse'))
    )
    op.create_table('post',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('cabinet_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinet.id'], name=op.f('fk_post_cabinet_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post')),
    sa.UniqueConstraint('cabinet_id', 'number', name=op.f('uq_post_cabinet_id'))
    )
    op.create_table('treatment_plan',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('diagnose_id', sa.Integer(), nullable=False),
    sa.Column('planned_session_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='treatmentplanstatus', native_enum=False), server_default='in_progress', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('planned_session_count >= 0', name=op.f('ck_treatment_plan_ck_planned_session_count_non_negative')),
    sa.ForeignKeyConstraint(['diagnose_id'], ['diagnose.id'], name=op.f('fk_treatment_plan_diagnose_id')),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], name=op.f('fk_treatment_plan_doctor_id')),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], name=op.f('fk_treatment_plan_patient_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_treatment_plan'))
    )
    op.create_index('ix_uq_active_patient_diagnose_plan', 'treatment_plan', ['patient_id', 'diagnose_id'], unique=True, postgresql_where=sa.text("status = 'IN_PROGRESS'"))
    op.create_table('session',
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('session_duration', sa.Integer(), nullable=False, comment='Session duration in seconds'),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='sessionstatus', native_enum=False), server_default='planned', nullable=False),
    sa.Column('ozone_concentration', sa.Float(), nullable=False, comment='mg/l'),
    sa.Column('nurse_id', sa.Integer(), nullable=True),
    sa.Column('treatment_plan_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurse.id'], name=op.f('fk_session_nurse_id')),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_session_post_id')),
    sa.ForeignKeyConstraint(['treatment_plan_id'], ['treatment_plan.id'], name=op.f('fk_session_treatment_plan_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session'))
    )
    op.create_index(op.f('ix_session_status'), 'session', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_status'), table_name='session')
    op.drop_table('session')
    op.drop_index('ix_uq_active_patient_diagnose_plan', table_name='treatment_plan', postgresql_where=sa.text("status = 'IN_PROGRESS'"))
    op.drop_table('treatment_plan')
    op.drop_table('post')
    op.drop_table('nurse')
    op.drop_table('doctor')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_table('user')
    op.drop_table('cabinet')
    op.drop_table('hospital')
    op.drop_index(op.f('ix_patient_phone'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_diagnose_name'), table_name='diagnose')
    op.drop_table('diagnose')
    op.drop_table('address')
    # ### end Alembic commands ###
